// Created by: Stuart Smith
// Student ID: S2336002
// Date Created: 2025-04-18
// Description:
// About page for the PC Build Recommendation System. Provides information about the project, data usage, and disclaimers.

import "../styles/About.css";

function About() {
  return (
    <div className="about-container">
      <h1 className="about-title">📚 About This Project</h1>

      <section className="about-section">
        <h2>🎯 Project Overview</h2>
        <p>
          This PC Build Recommendation System was developed as part of a Honours Project by Stuart Smith (Student ID: S2336002) at Glasgow Caledonian University.
          It provides users with personalized PC build suggestions based on their intended use and budget.
        </p>
      </section>

      <section className="about-section">
        <h2>📈 Data Usage</h2>
        <p>
          - Hardware data is sourced from publicly available datasets such as PassMark and UserBenchmark.<br />
          - No personal user data is collected or stored.<br />
          - Game system requirements, if applicable, are fetched from publicly available APIs.
        </p>
      </section>

      <section className="about-section">
        <h2>⚖️ Disclaimer</h2>
        <p>
          This tool is intended for educational and demonstration purposes only.<br />
          Suggested PC builds are generated by algorithmic matching and do not constitute professional hardware advice.<br />
          Performance and compatibility are not guaranteed.<br />
          All trademarks and product names are property of their respective owners.
        </p>
      </section>

      <section className="about-section">
        <h2>📧 Contact</h2>
        <p>
          For questions or inquiries regarding this project, please contact:<br />
          <strong>ssmith308@caledonian.ac.uk</strong>
        </p>
      </section>
    </div>
  );
}

export default About;